version: "3"
services:
  spring-app:
    build: ./
    ports:
      - "8087:8080"
    env_file: .env
    networks:
      - pagopa-ecommerce-net

networks:
  pagopa-ecommerce-net:
    name: pagopa-ecommerce-net
