variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
  PAGOPA_COMMONS_VERSION: 0.0.0 
  

trigger: none

pool:
  vmImage: ubuntu-latest

jobs: 
  - job: make_buildEndUnitTest
    steps:
      - script: | 
         ls
         cd pagopa-ecommerce-scheduler-service
         COMMONS_VERSION=$(mvn help:evaluate -Dexpression=pagopa-ecommerce-commons.version -q -DforceStdout)
         echo "${COMMONS_VERSION}"
         echo "##vso[task.setvariable variable=PAGOPA_COMMONS_VERSION]${COMMONS_VERSION}"
         echo "${PAGOPA_COMMONS_VERSION}"
      - checkout: https://github.com/pagopa/pagopa-ecommerce-commons@refs/tags/${PAGOPA_COMMONS_VERSION}
      - checkout: self
      - task: Cache@2
        inputs:
          key: 'maven | "$(Agent.OS)" | pagopa-ecommerce-scheduler-service/pom.xml'
          restoreKeys: |
            maven | "$(Agent.OS)"
            maven
          path: $(MAVEN_CACHE_FOLDER)
        displayName: Cache Maven local repo
      - task: Maven@3
        inputs:
          mavenPomFile: 'pagopa-ecommerce-commons/pom.xml'
          mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '17'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'clean install'
          sonarQubeRunAnalysis: false
      - task: SonarCloudPrepare@1
        displayName: 'Prepare SonarCloud analysis configuration'
        inputs:
          SonarCloud: '$(SONARCLOUD_SERVICE_CONN)'
          organization: '$(SONARCLOUD_ORG)'
          scannerMode: Other
          extraProperties: |
            sonar.projectKey=$(SONARCLOUD_PROJECT_KEY)
            sonar.projectName=$(SONARCLOUD_PROJECT_NAME)
            sonar.coverage.jacoco.xmlReportPaths=./target/site/jacoco/jacoco.xml
            sonar.junit.reportPaths=target/surefire-reports/
      - task: Maven@3
        inputs:
          mavenPomFile: 'pagopa-ecommerce-scheduler-service/pom.xml'
          options: '$(MAVEN_OPTS)'
          mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '17'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'clean verify'
          sonarQubeRunAnalysis: true
      - task: SonarCloudPublish@1
        displayName: 'Publish SonarCloud results on build summary'
        inputs:
          pollingTimeoutSec: '300'
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: 'JaCoCo'
          summaryFileLocation: 'target/site/jacoco/jacoco.xml'
          reportDirectory: 'target/site/jacoco'
        displayName: 'Publish Code Coverage on Azure Devops'
