parameters:
  - name: "RELEASE_FILTER"
    type: string
  - name: "KUBERNETES_SERVICE_CONN"
    type: string
  - name: "NAMESPACE"
    type: string

steps:
  - task: HelmDeploy@0
    displayName: List event dispatcher releases
    name: helm_event_dispatcher_releases
    inputs:
      kubernetesServiceEndpoint: ${{ parameters.KUBERNETES_SERVICE_CONN }}
      namespace: ${{ parameters.NAMESPACE }}
      command: ls
      arguments: --filter ${{ parameters.RELEASE_FILTER }} --output json
  - task: Bash@3
    name: helm_chart_version
    displayName: 'Retrieve helm chart version associated to helm release'
    inputs:
      targetType: "inline"
      script: |
        version=$(echo '$(helm_event_dispatcher_releases.helmOutput)' | yq '.[].chart' | sed -e 's/pagopa-ecommerce-event-dispatcher-//g')
        echo "##vso[task.setvariable variable=value;isOutput=true]$version"
      failOnStderr: true