#This template contains stages to handle zero downtime deploy swapping old-new deployments
parameters:
  # boolean parameter to effectively perform helm deploy task
  - name: "DO_DEPLOY"
    type: boolean
  # deploy environment
  - name: "ENV"
    type: string
    values:
      - DEV
      - UAT
      - PROD
  # the new version to be deployed
  - name: "NEW_VERSION"
    type: string
  # the application name to be used as a base name in helm new/old deployment
  - name: "APP_NAME"
    type: string
  # kubernetes service connection
  - name: "KUBERNETES_SERVICE_CONN"
    type: string
  # kubernetes cluster name
  - name: "KUBERNETES_CLUSTER"
    type: string
  # kubernetes namespace
  - name: "NAMESPACE"
    type: string
  # helm value file name
  - name: "VALUE_FILE"
    type: string
  # helm release filter to be used to detect the actual deployed version
  - name: "HELM_NEW_RELEASE_FILTER"
    type: string
  # deploy agent pool name to be used
  - name: "DEPLOY_AGENT_POOL_NAME"
    type: string
  #optional parameters
  # chart type
  - name: "CHART_TYPE"
    type: string
    default: "filepath"
  # chart path
  - name: "CHART_PATH"
    type: string
    default: "helm"
  # boolean value indicating if helm commands have to wait for execution completion
  - name: "WAIT_FOR_EXECUTION"
    type: boolean
    default: true
  # additional arguments to be used in helm deployment command
  - name: "ARGUMENTS"
    type: string
    default: "--timeout 5m0s"
stages:

  # STEP 0: retrieve current release version from helm release
  - stage: Current_Helm_Release_{{ parameters.ENV }}
    displayName: Retrieve current deployed helm release
    pool:
      name: ${{ parameters.DEPLOY_AGENT_POOL_NAME }}
    jobs:
      - job: list_event_dispatcher_helm_releases
        displayName: List event dispatcher helm releases
        steps:
          - task: HelmDeploy@0
            displayName: List event dispatcher releases
            name: helm_event_dispatcher_releases
            inputs:
              kubernetesServiceEndpoint: ${{ parameters.KUBERNETES_SERVICE_CONN }}
              namespace: ${{ parameters.NAMESPACE }}
              command: ls
              arguments: --filter ${{ parameters.HELM_NEW_RELEASE_FILTER }} --output json
          - task: Bash@3
            name: helm_chart_version
            displayName: 'Retrieve helm chart version associated to helm release'
            inputs:
              targetType: "inline"
              script: |
                version=$(echo '$(helm_event_dispatcher_releases.helmOutput)' | yq '.[].chart' | sed -e 's/pagopa-ecommerce-event-dispatcher-//g')
                echo "##vso[task.setvariable variable=helm_current_release_version;isOutput=true]$version"
              failOnStderr: false

  # STEP 1: deploy current PROD version as OLD release (used for rollback purpose)
  - stage: Old_Version_Deploy_Approval_{{ parameters.ENV }}
    displayName: Old version deploy approval
    dependsOn: Current_Helm_Release_{{ parameters.ENV }}
    condition: succeeded()
    pool: server
    variables:
      currentVersion: $[ stageDependencies.Current_Helm_Release_{{ parameters.ENV }}.list_event_dispatcher_helm_releases.outputs['helm_chart_version.helm_current_release_version'] ]
    jobs:
      - job: Old_Version_Deploy_Approval_{{ parameters.ENV }}
        displayName: Manual old version deploy approval
        timeoutInMinutes: 30
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 30
            inputs:
              notifyUsers: $(APPROVE_TOUCHPOINT_MAIL)
              instructions: "Approve upgrade OLD helm release to version: [$(currentVersion)]"
              onTimeout: 'reject'
  - stage: Old_Version_Deploy_{{ parameters.ENV }}
    dependsOn:
      - Current_Helm_Release_{{ parameters.ENV }}
      - Old_Version_Deploy_Approval_{{ parameters.ENV }}
    condition: succeeded()
    pool:
      name: ${{ parameters.DEPLOY_AGENT_POOL_NAME }}
    variables:
      currentVersion: $[ stageDependencies.Current_Helm_Release_{{ parameters.ENV }}.list_event_dispatcher_helm_releases.outputs['helm_chart_version.helm_current_release_version'] ]
    jobs:
      - deployment: Old_Version_Deploy_{{ parameters.ENV }}
        environment: ${{ parameters.ENV }}
        displayName: Deploy current prod version as OLD version
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    checkoutVersion=$(currentVersion)
                    echo "Checkout current version repo tag: [$checkoutVersion]" 
                    git checkout $checkoutVersion
                  displayName: 'Checkout currently deployed source code tag [$(currentVersion)]'
                - task: Bash@3
                  name: update_chart_version
                  displayName: 'Setup helm microservice chart'
                  inputs:
                    targetType: "inline"
                    script: |
                      helm repo add microservice-chart https://pagopa.github.io/aks-microservice-chart-blueprint
                      helm dep build helm
                - task: HelmDeploy@0
                  condition: and(succeeded(), eq(${{ parameters.DO_DEPLOY }}, True))
                  displayName: Deploy current PROD version $(currentVersion) as OLD release
                  inputs:
                    kubernetesServiceEndpoint: ${{ parameters.KUBERNETES_SERVICE_CONN }}
                    namespace: ${{ parameters.NAMESPACE }}
                    command: upgrade
                    chartType: ${{ parameters.CHART_TYPE }}
                    chartPath: ${{ parameters.CHART_PATH }}
                    chartName: ${{ parameters.APP_NAME }}-old
                    releaseName: ${{ parameters.APP_NAME }}-old
                    valueFile: ${{ parameters.VALUE_FILE }}
                    install: true
                    waitForExecution: ${{ parameters.WAIT_FOR_EXECUTION }}
                    arguments: ${{ parameters.ARGUMENTS }}
                    overrideValues: microservice-chart.ingress.path=/pagopa-ecommerce-event-dispatcher-old/(.*),microservice-chart.envConfig.DEPLOYMENT_VERSION=old

  # STEP 2: enable OLD deployment version receivers and stop new one by command curl
  - stage: Start_Old_Stop_New_Receivers_Manual_Approve_{{ parameters.ENV }}
    displayName: Start OLD receivers and stop new ones approval
    dependsOn: Old_Version_Deploy_{{ parameters.ENV }}
    pool: server
    jobs:
      - job: Start_Old_Stop_New_Receivers_Manual_Approve_{{ parameters.ENV }}
        displayName: Manual OLD receiver start and new stop approval
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 30
            inputs:
              notifyUsers: $(APPROVE_TOUCHPOINT_MAIL)
              instructions: "Approve enable OLD receivers"
              onTimeout: 'reject'
  - stage: Start_Old_Stop_New_Receivers_{{ parameters.ENV }}
    dependsOn: Start_Old_Stop_New_Receivers_Manual_Approve_{{ parameters.ENV }}
    condition: succeeded()
    pool:
      name: ${{ parameters.DEPLOY_AGENT_POOL_NAME }}
    jobs:
      - job: Start_Old_Stop_New_Receivers_{{ parameters.ENV }}
        steps:
          - template: start-receivers.yml
            parameters:
              DEPLOYMENT_INSTANCE_COMMAND_RECEIVER: old
              ENV: ${{ parameters.ENV }}
              TARGET_DEPLOYMENT_VERSION: OLD
          - template: stop-receivers.yml
            parameters:
              DEPLOYMENT_INSTANCE_COMMAND_RECEIVER: old
              ENV: ${{ parameters.ENV }}
              TARGET_DEPLOYMENT_VERSION: NEW


  # STEP 3: Deploy new release as Deployment NEW approval task
  - stage: Deploy_New_Version_Approval_{{ parameters.ENV }}
    displayName: Deploy the new release version ${{ parameters.NEW_VERSION }}
    dependsOn: Start_Old_Stop_New_Receivers_{{ parameters.ENV }}
    condition: succeeded()
    pool: server
    jobs:
      - job: New_Version_Deploy_Approval
        displayName: New version deploy manual approve
        timeoutInMinutes: 30
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 30
            inputs:
              notifyUsers: $(APPROVE_TOUCHPOINT_MAIL)
              instructions: "Approve upgrade NEW helm release to version: [${{ parameters.NEW_VERSION }}]"
              onTimeout: 'reject'
  - stage: Deploy_New_Version
    displayName: Deploy NEW version ${{ parameters.NEW_VERSION }}
    dependsOn: Deploy_New_Version_Approval_{{ parameters.ENV }}
    condition: succeeded()
    pool:
      name: ${{ parameters.DEPLOY_AGENT_POOL_NAME }}
    jobs:
      - deployment: New_Version_Deploy
        environment: ${{ parameters.ENV }}
        displayName: New version deploy
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    checkoutVersion=${{ parameters.NEW_VERSION }} 
                    echo "Checkout new release version repo tag: [$checkoutVersion]" 
                    git checkout $checkoutVersion
                  displayName: 'Checkout new release version tag [${{ parameters.NEW_VERSION }}]'
                - task: Bash@3
                  name: update_chart_version
                  displayName: 'Setup helm microservice chart'
                  inputs:
                    targetType: "inline"
                    script: |
                      helm repo add microservice-chart https://pagopa.github.io/aks-microservice-chart-blueprint
                      helm dep build helm
                - task: HelmDeploy@0
                  condition: and(succeeded(), eq(${{ parameters.DO_DEPLOY }}, True))
                  displayName: Deploy new version as NEW release
                  inputs:
                    kubernetesServiceEndpoint: ${{ parameters.KUBERNETES_SERVICE_CONN }}
                    namespace: ${{ parameters.NAMESPACE }}
                    command: upgrade
                    chartType: ${{ parameters.CHART_TYPE }}
                    chartPath: ${{ parameters.CHART_PATH }}
                    chartName: ${{ parameters.APP_NAME }}-new
                    releaseName: ${{ parameters.APP_NAME }}-new
                    valueFile: ${{ parameters.VALUE_FILE }}
                    install: true
                    waitForExecution: ${{ parameters.WAIT_FOR_EXECUTION }}
                    arguments: ${{ parameters.ARGUMENTS }}
                    overrideValues: microservice-chart.ingress.path=/pagopa-ecommerce-event-dispatcher-new/(.*),microservice-chart.envConfig.DEPLOYMENT_VERSION=new

  # STEP 4: once new version is deployed, proceed to start new receivers and stop old ones
  - stage: Start_New_Stop_Old_Receivers_Approval_{{ parameters.ENV }}
    displayName: Start new receivers and stop old ones manual approval
    dependsOn: Deploy_New_Version
    pool: server
    jobs:
      - job: Start_New_Stop_Old_Receivers_Approval_{{ parameters.ENV }}
        timeoutInMinutes: 30
        displayName: Start new receivers and stop old ones
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 30
            inputs:
              notifyUsers: $(APPROVE_TOUCHPOINT_MAIL)
              instructions: "Approve enable NEW receivers and disable old ones"
              onTimeout: 'reject'
  - stage: Start_New_Stop_Old_Receivers_{{ parameters.ENV }}
    displayName: Start new receivers and stop old ones
    dependsOn: Start_New_Stop_Old_Receivers_Approval_{{ parameters.ENV }}
    condition: succeeded()
    pool:
      name: ${{ parameters.DEPLOY_AGENT_POOL_NAME }}
    jobs:
      - job: Start_New_Stop_Old_Receivers_{{ parameters.ENV }}
        displayName: Start new receivers by curl command and stop old ones
        steps:
          - template: start-receivers.yml
            parameters:
              DEPLOYMENT_INSTANCE_COMMAND_RECEIVER: new
              ENV: ${{ parameters.ENV }}
              TARGET_DEPLOYMENT_VERSION: NEW
          - template: stop-receivers.yml
            parameters:
              DEPLOYMENT_INSTANCE_COMMAND_RECEIVER: new
              ENV: ${{ parameters.ENV }}
              TARGET_DEPLOYMENT_VERSION: OLD


  # STEP 5: deployment rollout ended, scale down OLD deployment PODS
  - stage: Scale_Down_Old_Deployment_Approval_{{ parameters.ENV }}
    dependsOn: Start_New_Stop_Old_Receivers_{{ parameters.ENV }}
    displayName: Approval for scale down old deployment PODS
    pool: server
    jobs:
      - job: Scale_Down_Old_Deployment_Approval_{{ parameters.ENV }}
        timeoutInMinutes: 30
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 4320 # 3 days
            inputs:
              notifyUsers: $(APPROVE_TOUCHPOINT_MAIL)
              instructions: "Approve scale OLD deployment down to 0 pods"
              onTimeout: 'reject'
  - stage: Scale_Down_Old_Deployment_{{ parameters.ENV }}
    dependsOn: Scale_Down_Old_Deployment_Approval_{{ parameters.ENV }}
    displayName: Scale down OLD deployment to 0 pods
    pool:
      name: ${{ parameters.DEPLOY_AGENT_POOL_NAME }}
    jobs:
      - job: Scale_Down_Old_Deployment_{{ parameters.ENV }}
        displayName: Annotate scaledObject with autoscaling.keda.sh/paused-replicas="0"
        steps:
          - task: Kubernetes@1
            displayName: Scale down old receivers PODS (annotate ScaledObject with autoscaling.keda.sh/paused-replicas="0")
            continueOnError: true
            inputs:
              kubernetesServiceEndpoint: ${{ parameters.KUBERNETES_SERVICE_CONN }}
              kubernetesCluster: ${{ parameters.KUBERNETES_CLUSTER }}
              namespace: ${{ parameters.NAMESPACE }}
              command: annotate
              arguments: scaledobjects ${{ parameters.APP_NAME }}-old-microservice-chart autoscaling.keda.sh/paused-replicas="0"

