microservice-chart:
  namespace: "ecommerce"
  nameOverride: ""
  fullnameOverride: ""
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: bluegreen
    service:
      create: true
    deployment:
      create: true
      image:
        repository: pagopapcommonacr.azurecr.io/pagopaecommerceeventdispatcherservice
        tag: "latest"
        pullPolicy: Always
    envConfig:
      TRANSACTIONS_CLOSE_PAYMENT_QUEUE_NAME: pagopa-p-weu-ecommerce-transactions-close-payment-queue
      TRANSACTIONS_CLOSE_PAYMENT_RETRY_QUEUE_NAME: pagopa-p-weu-ecommerce-transactions-close-payment-retry-queue
      TRANSACTIONS_EXPIRATION_QUEUE_NAME: pagopa-p-weu-ecommerce-transactions-expiration-queue
      TRANSACTIONS_REFUND_RETRY_QUEUE_NAME: pagopa-p-weu-ecommerce-transactions-refund-retry-queue
      TRANSACTIONS_REFUND_QUEUE_NAME: pagopa-p-weu-ecommerce-transactions-refund-queue
      TRANSACTIONS_NOTIFICATIONS_RETRY_QUEUE_NAME: pagopa-p-weu-ecommerce-transaction-notifications-retry-queue
      TRANSACTIONS_NOTIFICATIONS_QUEUE_NAME: pagopa-p-weu-ecommerce-transaction-notifications-queue
      TRANSACTIONS_DEAD_LETTER_QUEUE_NAME: pagopa-p-weu-ecommerce-transactions-dead-letter-queue
      PAYMENT_TRANSACTIONS_GATEWAY_URI: https://api.platform.pagopa.it/payment-transactions-gateway/internal/v1
      PAYMENT_TRANSACTIONS_GATEWAY_READ_TIMEOUT: "10000"
      PAYMENT_TRANSACTIONS_GATEWAY_CONNECTION_TIMEOUT: "10000"
      NODO_URI: https://api.platform.pagopa.it/nodo/nodo-per-pm/v2
      NODO_READ_TIMEOUT: "10000"
      NODO_CONNECTION_TIMEOUT: "10000"
      NODO_ECOMMERCE_CLIENT_ID: ecomm
      MONGO_HOST: pagopa-p-weu-ecommerce-cosmos-account.mongo.cosmos.azure.com
      MONGO_USERNAME: pagopa-p-weu-ecommerce-cosmos-account
      MONGO_PORT: "10255"
      MONGO_SSL_ENABLED: "true"
      REDIS_HOST: pagopa-p-weu-ecommerce-redis.redis.cache.windows.net
      REDIS_PORT: "6380"
      REDIS_SSL_ENABLED: "true"
      ECOMMERCE_STORAGE_TRANSIENT_QUEUE_ACCOUNT_NAME: pagopapweuecommercetrsa
      ECOMMERCE_STORAGE_TRANSIENT_QUEUE_ENDPOINT: https://pagopapweuecommercetrsa.queue.core.windows.net/pagopauweuecommercetrsa
      REFUND_RETRY_EVENT_BASE_INTERVAL_SECONDS: "600"
      REFUND_RETRY_EVENT_MAX_ATTEMPTS: "3"
      CLOSE_PAYMENT_RETRY_EVENT_BASE_INTERVAL_SECONDS: "30"
      CLOSE_PAYMENT_RETRY_EVENT_MAX_ATTEMPTS: "3"
      NOTIFICATION_RETRY_EVENT_BASE_INTERVAL_SECONDS: "600"
      NOTIFICATION_RETRY_EVENT_MAX_ATTEMPTS: "3"
      NOTIFICATIONS_SERVICE_URI: https://api.platform.pagopa.it/ecommerce/notifications-service/v1
      NOTIFICATIONS_SERVICE_READ_TIMEOUT: "10000"
      NOTIFICATIONS_SERVICE_CONNECTION_TIMEOUT: "10000"
      PERSONAL_DATA_VAULT_API_BASE_PATH: "https://api.tokenizer.pdv.pagopa.it/tokenizer/v1"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopa-ecommerce-event-dispatcher-service-blue,service.deployment.environment=prod"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
      OTEL_TRACES_SAMPLER: "always_on"
      SEND_PAYMENT_RESULT_TIMEOUT_SECONDS: "3900"
      SEND_PAYMENT_RESULT_EXPIRATION_OFFSET_SECONDS: "5"
      TRANSIENT_QUEUES_TTL_SECONDS: "2592000"
      NPG_URI: https://xpay.nexigroup.com/api/phoenix-0.0
      NPG_READ_TIMEOUT: "10000"
      NPG_CONNECTION_TIMEOUT: "10000"
      ECS_SERVICE_NAME: pagopa-ecommerce-event-dispatcher-service-blue
      ECS_SERVICE_ENVIRONMENT: prod
    envSecret:
      ECOMMERCE_STORAGE_TRANSIENT_QUEUE_KEY: ecommerce-storage-transient-account-key
      MONGO_PASSWORD: mongo-ecommerce-password
      REDIS_PASSWORD: redis-ecommerce-password
      NODO_CONNECTION_STRING: nodo-connection-string
      QUEUE_TRANSIENT_CONNECTION_STRING: ecommerce-storage-transient-connection-string
      QUEUE_DEADLETTER_CONNECTION_STRING: ecommerce-storage-deadletter-connection-string
      NOTIFICATIONS_SERVICE_API_KEY: notifications-service-api-key
      PERSONAL_DATA_VAULT_API_KEY: personal-data-vault-api-key
      OTEL_EXPORTER_OTLP_HEADERS: elastic-otel-token-header
      PAYMENT_TRANSACTIONS_GATEWAY_API_KEY: payment-transactions-gateway-api-key
      NPG_API_KEY: npg-api-key
  image:
    repository: pagopapcommonacr.azurecr.io/pagopaecommerceeventdispatcherservice
    tag: "0.10.4"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 9000
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 9000
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  service:
    create: true
    type: ClusterIP
    ports:
      - 9000
  ingress:
    create: true
    host: "weuprod.ecommerce.internal.platform.pagopa.it"
    path: /pagopa-ecommerce-event-dispatcher/(.*)
    servicePort: 9000
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  autoscaling:
    enabled: true
    minReplica: 2
    maxReplica: 10
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
  envConfig:
    TRANSACTIONS_CLOSE_PAYMENT_QUEUE_NAME: pagopa-p-weu-ecommerce-transactions-close-payment-queue
    TRANSACTIONS_CLOSE_PAYMENT_RETRY_QUEUE_NAME: pagopa-p-weu-ecommerce-transactions-close-payment-retry-queue
    TRANSACTIONS_EXPIRATION_QUEUE_NAME: pagopa-p-weu-ecommerce-transactions-expiration-queue
    TRANSACTIONS_REFUND_RETRY_QUEUE_NAME: pagopa-p-weu-ecommerce-transactions-refund-retry-queue
    TRANSACTIONS_REFUND_QUEUE_NAME: pagopa-p-weu-ecommerce-transactions-refund-queue
    TRANSACTIONS_NOTIFICATIONS_RETRY_QUEUE_NAME: pagopa-p-weu-ecommerce-transaction-notifications-retry-queue
    TRANSACTIONS_NOTIFICATIONS_QUEUE_NAME: pagopa-p-weu-ecommerce-transaction-notifications-queue
    TRANSACTIONS_DEAD_LETTER_QUEUE_NAME: pagopa-p-weu-ecommerce-transactions-dead-letter-queue
    PAYMENT_TRANSACTIONS_GATEWAY_URI: https://api.platform.pagopa.it/payment-transactions-gateway/internal/v1
    PAYMENT_TRANSACTIONS_GATEWAY_READ_TIMEOUT: "10000"
    PAYMENT_TRANSACTIONS_GATEWAY_CONNECTION_TIMEOUT: "10000"
    NODO_URI: https://api.platform.pagopa.it/nodo/nodo-per-pm/v2
    NODO_READ_TIMEOUT: "10000"
    NODO_CONNECTION_TIMEOUT: "10000"
    NODO_ECOMMERCE_CLIENT_ID: ecomm
    MONGO_HOST: pagopa-p-weu-ecommerce-cosmos-account.mongo.cosmos.azure.com
    MONGO_USERNAME: pagopa-p-weu-ecommerce-cosmos-account
    MONGO_PORT: "10255"
    MONGO_SSL_ENABLED: "true"
    REDIS_HOST: pagopa-p-weu-ecommerce-redis.redis.cache.windows.net
    REDIS_PORT: "6380"
    REDIS_SSL_ENABLED: "true"
    ECOMMERCE_STORAGE_TRANSIENT_QUEUE_ACCOUNT_NAME: pagopapweuecommercetrsa
    ECOMMERCE_STORAGE_TRANSIENT_QUEUE_ENDPOINT: https://pagopapweuecommercetrsa.queue.core.windows.net/pagopapweuecommercetrsa
    REFUND_RETRY_EVENT_BASE_INTERVAL_SECONDS: "600"
    REFUND_RETRY_EVENT_MAX_ATTEMPTS: "3"
    CLOSE_PAYMENT_RETRY_EVENT_BASE_INTERVAL_SECONDS: "30"
    CLOSE_PAYMENT_RETRY_EVENT_MAX_ATTEMPTS: "3"
    NOTIFICATION_RETRY_EVENT_BASE_INTERVAL_SECONDS: "600"
    NOTIFICATION_RETRY_EVENT_MAX_ATTEMPTS: "3"
    NOTIFICATIONS_SERVICE_URI: https://api.platform.pagopa.it/ecommerce/notifications-service/v1
    NOTIFICATIONS_SERVICE_READ_TIMEOUT: "10000"
    NOTIFICATIONS_SERVICE_CONNECTION_TIMEOUT: "10000"
    PERSONAL_DATA_VAULT_API_BASE_PATH: "https://api.tokenizer.pdv.pagopa.it/tokenizer/v1"
    OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopa-ecommerce-event-dispatcher-service,service.deployment.environment=prod"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: otlp
    OTEL_TRACES_SAMPLER: "always_on"
    SEND_PAYMENT_RESULT_TIMEOUT_SECONDS: "3900"
    SEND_PAYMENT_RESULT_EXPIRATION_OFFSET_SECONDS: "5"
    ECS_SERVICE_NAME: pagopa-ecommerce-event-dispatcher-service
    ECS_SERVICE_ENVIRONMENT: prod
    TRANSIENT_QUEUES_TTL_SECONDS: "2592000"
    NPG_URI: https://xpay.nexigroup.com/api/phoenix-0.0
    NPG_READ_TIMEOUT: "10000"
    NPG_CONNECTION_TIMEOUT: "10000"
  envSecret:
    ECOMMERCE_STORAGE_TRANSIENT_QUEUE_KEY: ecommerce-storage-transient-account-key
    MONGO_PASSWORD: mongo-ecommerce-password
    REDIS_PASSWORD: redis-ecommerce-password
    NODO_CONNECTION_STRING: nodo-connection-string
    QUEUE_TRANSIENT_CONNECTION_STRING: ecommerce-storage-transient-connection-string
    QUEUE_DEADLETTER_CONNECTION_STRING: ecommerce-storage-deadletter-connection-string
    NOTIFICATIONS_SERVICE_API_KEY: notifications-service-api-key
    PERSONAL_DATA_VAULT_API_KEY: personal-data-vault-api-key
    OTEL_EXPORTER_OTLP_HEADERS: elastic-otel-token-header
    PAYMENT_TRANSACTIONS_GATEWAY_API_KEY: payment-transactions-gateway-api-key
    NPG_API_KEY: npg-api-key
  keyvault:
    name: "pagopa-p-ecommerce-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
